<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.trae.foundation.minecraft.velocity</groupId>
        <artifactId>Minecraft-Velocity</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>Minecraft-Velocity-Plugin-Framework</artifactId>

    <dependencies>
        <!-- Utilities -->
        <dependency>
            <groupId>me.trae.foundation</groupId>
            <artifactId>Utilities</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- Injector API -->
        <dependency>
            <groupId>me.trae.foundation.injector</groupId>
            <artifactId>Injector-API</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- Injector Core -->
        <dependency>
            <groupId>me.trae.foundation.injector</groupId>
            <artifactId>Injector-Core</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Injector Commons Extension -->
        <dependency>
            <groupId>me.trae.foundation.injector.extensions</groupId>
            <artifactId>Injector-Commons-Extension</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- Injector Scheduler Extension -->
        <dependency>
            <groupId>me.trae.foundation.injector.extensions</groupId>
            <artifactId>Injector-Scheduler-Extension</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- Injector Configuration Extension -->
        <dependency>
            <groupId>me.trae.foundation.injector.extensions</groupId>
            <artifactId>Injector-Configuration-Extension</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- Minecraft Common -->
        <dependency>
            <groupId>me.trae.foundation.minecraft</groupId>
            <artifactId>Minecraft-Common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Velocity API -->
        <dependency>
            <groupId>com.velocitypowered</groupId>
            <artifactId>velocity-api</artifactId>
            <version>${velocity.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>