package me.trae.foundation.minecraft.paper.plugin.framework.utility;

import lombok.experimental.UtilityClass;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

@UtilityClass
public class UtilMaterial {

    public static boolean isInteractable(final Material material) {
        return switch (material) {
            case ACACIA_BUTTON, ACACIA_DOOR, ACACIA_FENCE_GATE, ACACIA_HANGING_SIGN, ACACIA_SHELF, ACACIA_SIGN, ACACIA_TRAPDOOR, ACACIA_WALL_HANGING_SIGN, ACACIA_WALL_SIGN, ANVIL,
                 BAMBOO_BUTTON, BAMBOO_DOOR, BAMBOO_FENCE_GATE, BAMBOO_HANGING_SIGN, BAMBOO_SHELF, BAMBOO_SIGN, BAMBOO_TRAPDOOR, BAMBOO_WALL_HANGING_SIGN, BAMBOO_WALL_SIGN, BARREL, BEACON, BELL,
                 BIRCH_BUTTON, BIRCH_DOOR, BIRCH_FENCE_GATE, BIRCH_HANGING_SIGN, BIRCH_SHELF, BIRCH_SIGN, BIRCH_TRAPDOOR, BIRCH_WALL_HANGING_SIGN, BIRCH_WALL_SIGN,
                 BLACK_BED, BLACK_CANDLE, BLACK_CANDLE_CAKE, BLACK_SHULKER_BOX, BLAST_FURNACE, BLUE_BED, BLUE_CANDLE, BLUE_CANDLE_CAKE, BLUE_SHULKER_BOX, BREWING_STAND, BROWN_BED, BROWN_CANDLE, BROWN_CANDLE_CAKE, BROWN_SHULKER_BOX,
                 CAKE, CAMPFIRE, CANDLE, CANDLE_CAKE, CARTOGRAPHY_TABLE, CAULDRON,
                 CHERRY_BUTTON, CHERRY_DOOR, CHERRY_FENCE_GATE, CHERRY_HANGING_SIGN, CHERRY_SHELF, CHERRY_SIGN, CHERRY_TRAPDOOR, CHERRY_WALL_HANGING_SIGN, CHERRY_WALL_SIGN,
                 CHEST, CHIPPED_ANVIL, CHISELED_BOOKSHELF, COMPARATOR, COMPOSTER, COPPER_CHEST, COPPER_DOOR, COPPER_GOLEM_STATUE, COPPER_TRAPDOOR, CRAFTER, CRAFTING_TABLE,
                 CRIMSON_BUTTON, CRIMSON_DOOR, CRIMSON_FENCE_GATE, CRIMSON_HANGING_SIGN, CRIMSON_SHELF, CRIMSON_SIGN, CRIMSON_TRAPDOOR, CRIMSON_WALL_HANGING_SIGN, CRIMSON_WALL_SIGN,
                 CYAN_BED, CYAN_CANDLE, CYAN_CANDLE_CAKE, CYAN_SHULKER_BOX, DAMAGED_ANVIL,
                 DARK_OAK_BUTTON, DARK_OAK_DOOR, DARK_OAK_FENCE_GATE, DARK_OAK_HANGING_SIGN, DARK_OAK_SHELF, DARK_OAK_SIGN, DARK_OAK_TRAPDOOR, DARK_OAK_WALL_HANGING_SIGN, DARK_OAK_WALL_SIGN,
                 DAYLIGHT_DETECTOR, DECORATED_POT, DISPENSER, DROPPER, ENCHANTING_TABLE, ENDER_CHEST,
                 EXPOSED_COPPER_CHEST, EXPOSED_COPPER_DOOR, EXPOSED_COPPER_GOLEM_STATUE, EXPOSED_COPPER_TRAPDOOR, FLETCHING_TABLE, FLOWER_POT, FURNACE,
                 GRAY_BED, GRAY_CANDLE, GRAY_CANDLE_CAKE, GRAY_SHULKER_BOX, GREEN_BED, GREEN_CANDLE, GREEN_CANDLE_CAKE, GREEN_SHULKER_BOX, GRINDSTONE, HOPPER, JUKEBOX,
                 JUNGLE_BUTTON, JUNGLE_DOOR, JUNGLE_FENCE_GATE, JUNGLE_HANGING_SIGN, JUNGLE_SHELF, JUNGLE_SIGN, JUNGLE_TRAPDOOR, JUNGLE_WALL_HANGING_SIGN, JUNGLE_WALL_SIGN,
                 LAVA_CAULDRON, LECTERN, LEVER, LIGHT_BLUE_BED, LIGHT_BLUE_CANDLE, LIGHT_BLUE_CANDLE_CAKE, LIGHT_BLUE_SHULKER_BOX, LIGHT_GRAY_BED, LIGHT_GRAY_CANDLE, LIGHT_GRAY_CANDLE_CAKE, LIGHT_GRAY_SHULKER_BOX,
                 LIME_BED, LIME_CANDLE, LIME_CANDLE_CAKE, LIME_SHULKER_BOX, LOOM, MAGENTA_BED, MAGENTA_CANDLE, MAGENTA_CANDLE_CAKE, MAGENTA_SHULKER_BOX,
                 MANGROVE_BUTTON, MANGROVE_DOOR, MANGROVE_FENCE_GATE, MANGROVE_HANGING_SIGN, MANGROVE_SHELF, MANGROVE_SIGN, MANGROVE_TRAPDOOR, MANGROVE_WALL_HANGING_SIGN, MANGROVE_WALL_SIGN, NOTE_BLOCK,
                 OAK_BUTTON, OAK_DOOR, OAK_FENCE_GATE, OAK_HANGING_SIGN, OAK_SHELF, OAK_SIGN, OAK_TRAPDOOR, OAK_WALL_HANGING_SIGN, OAK_WALL_SIGN,
                 ORANGE_BED, ORANGE_CANDLE, ORANGE_CANDLE_CAKE, ORANGE_SHULKER_BOX, OXIDIZED_COPPER_CHEST, OXIDIZED_COPPER_DOOR, OXIDIZED_COPPER_GOLEM_STATUE, OXIDIZED_COPPER_TRAPDOOR,
                 PALE_OAK_BUTTON, PALE_OAK_DOOR, PALE_OAK_FENCE_GATE, PALE_OAK_HANGING_SIGN, PALE_OAK_SHELF, PALE_OAK_SIGN, PALE_OAK_TRAPDOOR, PALE_OAK_WALL_HANGING_SIGN, PALE_OAK_WALL_SIGN,
                 PINK_BED, PINK_CANDLE, PINK_CANDLE_CAKE, PINK_SHULKER_BOX, POLISHED_BLACKSTONE_BUTTON,
                 POTTED_ACACIA_SAPLING, POTTED_ALLIUM, POTTED_AZALEA_BUSH, POTTED_AZURE_BLUET, POTTED_BAMBOO, POTTED_BIRCH_SAPLING, POTTED_BLUE_ORCHID, POTTED_BROWN_MUSHROOM, POTTED_CACTUS, POTTED_CHERRY_SAPLING,
                 POTTED_CLOSED_EYEBLOSSOM, POTTED_CORNFLOWER, POTTED_CRIMSON_FUNGUS, POTTED_CRIMSON_ROOTS, POTTED_DANDELION, POTTED_DARK_OAK_SAPLING, POTTED_DEAD_BUSH, POTTED_FERN, POTTED_FLOWERING_AZALEA_BUSH,
                 POTTED_JUNGLE_SAPLING, POTTED_LILY_OF_THE_VALLEY, POTTED_MANGROVE_PROPAGULE, POTTED_OAK_SAPLING, POTTED_OPEN_EYEBLOSSOM, POTTED_ORANGE_TULIP, POTTED_OXEYE_DAISY, POTTED_PALE_OAK_SAPLING,
                 POTTED_PINK_TULIP, POTTED_POPPY, POTTED_RED_MUSHROOM, POTTED_RED_TULIP, POTTED_SPRUCE_SAPLING, POTTED_TORCHFLOWER, POTTED_WARPED_FUNGUS, POTTED_WARPED_ROOTS, POTTED_WHITE_TULIP, POTTED_WITHER_ROSE,
                 POWDER_SNOW_CAULDRON, PURPLE_BED, PURPLE_CANDLE, PURPLE_CANDLE_CAKE, PURPLE_SHULKER_BOX,
                 RED_BED, RED_CANDLE, RED_CANDLE_CAKE, RED_SHULKER_BOX, REPEATER, RESPAWN_ANCHOR, SHULKER_BOX, SMITHING_TABLE, SMOKER, SOUL_CAMPFIRE,
                 SPRUCE_BUTTON, SPRUCE_DOOR, SPRUCE_FENCE_GATE, SPRUCE_HANGING_SIGN, SPRUCE_SHELF, SPRUCE_SIGN, SPRUCE_TRAPDOOR, SPRUCE_WALL_HANGING_SIGN, SPRUCE_WALL_SIGN,
                 STONE_BUTTON, STONECUTTER, TRAPPED_CHEST, VAULT,
                 WARPED_BUTTON, WARPED_DOOR, WARPED_FENCE_GATE, WARPED_HANGING_SIGN, WARPED_SHELF, WARPED_SIGN, WARPED_TRAPDOOR, WARPED_WALL_HANGING_SIGN, WARPED_WALL_SIGN, WATER_CAULDRON,
                 WAXED_COPPER_CHEST, WAXED_COPPER_DOOR, WAXED_COPPER_GOLEM_STATUE, WAXED_COPPER_TRAPDOOR, WAXED_EXPOSED_COPPER_CHEST, WAXED_EXPOSED_COPPER_DOOR, WAXED_EXPOSED_COPPER_GOLEM_STATUE, WAXED_EXPOSED_COPPER_TRAPDOOR,
                 WAXED_OXIDIZED_COPPER_CHEST, WAXED_OXIDIZED_COPPER_DOOR, WAXED_OXIDIZED_COPPER_GOLEM_STATUE, WAXED_OXIDIZED_COPPER_TRAPDOOR, WAXED_WEATHERED_COPPER_CHEST, WAXED_WEATHERED_COPPER_DOOR, WAXED_WEATHERED_COPPER_GOLEM_STATUE, WAXED_WEATHERED_COPPER_TRAPDOOR,
                 WEATHERED_COPPER_CHEST, WEATHERED_COPPER_DOOR, WEATHERED_COPPER_GOLEM_STATUE, WEATHERED_COPPER_TRAPDOOR,
                 WHITE_BED, WHITE_CANDLE, WHITE_CANDLE_CAKE, WHITE_SHULKER_BOX, YELLOW_BED, YELLOW_CANDLE, YELLOW_CANDLE_CAKE, YELLOW_SHULKER_BOX -> true;
            default -> false;
        };
    }

    public static boolean isInteractableByHand(final Material material, final ItemStack itemStack) {
        return switch (itemStack.getType()) {
            case WOODEN_AXE, STONE_AXE, COPPER_AXE, IRON_AXE, GOLDEN_AXE, DIAMOND_AXE, NETHERITE_AXE -> switch (material) {
                case ACACIA_LOG, ACACIA_WOOD, BAMBOO_BLOCK, BIRCH_LOG, BIRCH_WOOD, CHERRY_LOG, CHERRY_WOOD, CRIMSON_HYPHAE, CRIMSON_STEM, DARK_OAK_LOG, DARK_OAK_WOOD, JUNGLE_LOG, JUNGLE_WOOD, MANGROVE_LOG, MANGROVE_WOOD, OAK_LOG, OAK_WOOD, PALE_OAK_LOG, PALE_OAK_WOOD, SPRUCE_LOG, SPRUCE_WOOD, WARPED_HYPHAE, WARPED_STEM,
                     CHISELED_COPPER, COPPER_BARS, COPPER_BLOCK, COPPER_BULB, COPPER_CHAIN, COPPER_CHEST, COPPER_DOOR, COPPER_GOLEM_STATUE, COPPER_GRATE, COPPER_LANTERN, COPPER_TRAPDOOR, CUT_COPPER, CUT_COPPER_SLAB, CUT_COPPER_STAIRS, LIGHTNING_ROD,
                     EXPOSED_CHISELED_COPPER, EXPOSED_COPPER, EXPOSED_COPPER_BARS, EXPOSED_COPPER_BULB, EXPOSED_COPPER_CHAIN, EXPOSED_COPPER_CHEST, EXPOSED_COPPER_DOOR, EXPOSED_COPPER_GOLEM_STATUE, EXPOSED_COPPER_GRATE, EXPOSED_COPPER_LANTERN, EXPOSED_COPPER_TRAPDOOR, EXPOSED_CUT_COPPER, EXPOSED_CUT_COPPER_SLAB, EXPOSED_CUT_COPPER_STAIRS, EXPOSED_LIGHTNING_ROD,
                     WEATHERED_CHISELED_COPPER, WEATHERED_COPPER, WEATHERED_COPPER_BARS, WEATHERED_COPPER_BULB, WEATHERED_COPPER_CHAIN, WEATHERED_COPPER_CHEST, WEATHERED_COPPER_DOOR, WEATHERED_COPPER_GOLEM_STATUE, WEATHERED_COPPER_GRATE, WEATHERED_COPPER_LANTERN, WEATHERED_COPPER_TRAPDOOR, WEATHERED_CUT_COPPER, WEATHERED_CUT_COPPER_SLAB, WEATHERED_CUT_COPPER_STAIRS, WEATHERED_LIGHTNING_ROD,
                     OXIDIZED_CHISELED_COPPER, OXIDIZED_COPPER, OXIDIZED_COPPER_BARS, OXIDIZED_COPPER_BULB, OXIDIZED_COPPER_CHAIN, OXIDIZED_COPPER_CHEST, OXIDIZED_COPPER_DOOR, OXIDIZED_COPPER_GOLEM_STATUE, OXIDIZED_COPPER_GRATE, OXIDIZED_COPPER_LANTERN, OXIDIZED_COPPER_TRAPDOOR, OXIDIZED_CUT_COPPER, OXIDIZED_CUT_COPPER_SLAB, OXIDIZED_CUT_COPPER_STAIRS, OXIDIZED_LIGHTNING_ROD,
                     WAXED_CHISELED_COPPER, WAXED_COPPER_BARS, WAXED_COPPER_BLOCK, WAXED_COPPER_BULB, WAXED_COPPER_CHAIN, WAXED_COPPER_CHEST, WAXED_COPPER_DOOR, WAXED_COPPER_GOLEM_STATUE, WAXED_COPPER_GRATE, WAXED_COPPER_LANTERN, WAXED_COPPER_TRAPDOOR, WAXED_CUT_COPPER, WAXED_CUT_COPPER_SLAB, WAXED_CUT_COPPER_STAIRS, WAXED_LIGHTNING_ROD,
                     WAXED_EXPOSED_CHISELED_COPPER, WAXED_EXPOSED_COPPER, WAXED_EXPOSED_COPPER_BARS, WAXED_EXPOSED_COPPER_BULB, WAXED_EXPOSED_COPPER_CHAIN, WAXED_EXPOSED_COPPER_CHEST, WAXED_EXPOSED_COPPER_DOOR, WAXED_EXPOSED_COPPER_GOLEM_STATUE, WAXED_EXPOSED_COPPER_GRATE, WAXED_EXPOSED_COPPER_LANTERN, WAXED_EXPOSED_COPPER_TRAPDOOR, WAXED_EXPOSED_CUT_COPPER, WAXED_EXPOSED_CUT_COPPER_SLAB, WAXED_EXPOSED_CUT_COPPER_STAIRS, WAXED_EXPOSED_LIGHTNING_ROD,
                     WAXED_WEATHERED_CHISELED_COPPER, WAXED_WEATHERED_COPPER, WAXED_WEATHERED_COPPER_BARS, WAXED_WEATHERED_COPPER_BULB, WAXED_WEATHERED_COPPER_CHAIN, WAXED_WEATHERED_COPPER_CHEST, WAXED_WEATHERED_COPPER_DOOR, WAXED_WEATHERED_COPPER_GOLEM_STATUE, WAXED_WEATHERED_COPPER_GRATE, WAXED_WEATHERED_COPPER_LANTERN, WAXED_WEATHERED_COPPER_TRAPDOOR, WAXED_WEATHERED_CUT_COPPER, WAXED_WEATHERED_CUT_COPPER_SLAB, WAXED_WEATHERED_CUT_COPPER_STAIRS, WAXED_WEATHERED_LIGHTNING_ROD,
                     WAXED_OXIDIZED_CHISELED_COPPER, WAXED_OXIDIZED_COPPER, WAXED_OXIDIZED_COPPER_BARS, WAXED_OXIDIZED_COPPER_BULB, WAXED_OXIDIZED_COPPER_CHAIN, WAXED_OXIDIZED_COPPER_CHEST, WAXED_OXIDIZED_COPPER_DOOR, WAXED_OXIDIZED_COPPER_GOLEM_STATUE, WAXED_OXIDIZED_COPPER_GRATE, WAXED_OXIDIZED_COPPER_LANTERN, WAXED_OXIDIZED_COPPER_TRAPDOOR, WAXED_OXIDIZED_CUT_COPPER, WAXED_OXIDIZED_CUT_COPPER_SLAB, WAXED_OXIDIZED_CUT_COPPER_STAIRS, WAXED_OXIDIZED_LIGHTNING_ROD -> true;
                default -> false;
            };
            case WOODEN_HOE, STONE_HOE, COPPER_HOE, IRON_HOE, GOLDEN_HOE, DIAMOND_HOE, NETHERITE_HOE -> switch (material) {
                case DIRT, COARSE_DIRT, ROOTED_DIRT, GRASS_BLOCK, PODZOL, MYCELIUM, DIRT_PATH -> true;
                default -> false;
            };
            case WOODEN_SHOVEL, STONE_SHOVEL, COPPER_SHOVEL, IRON_SHOVEL, GOLDEN_SHOVEL, DIAMOND_SHOVEL, NETHERITE_SHOVEL -> switch (material) {
                case DIRT, COARSE_DIRT, ROOTED_DIRT, GRASS_BLOCK, PODZOL, MYCELIUM, CAMPFIRE, SOUL_CAMPFIRE -> true;
                default -> false;
            };
            case BONE_MEAL -> switch (material) {
                case ACACIA_SAPLING, BIRCH_SAPLING, CHERRY_SAPLING, DARK_OAK_SAPLING, JUNGLE_SAPLING, MANGROVE_PROPAGULE, OAK_SAPLING, PALE_OAK_SAPLING, SPRUCE_SAPLING, AZALEA, FLOWERING_AZALEA,
                     WHEAT, CARROTS, POTATOES, BEETROOTS, MELON_STEM, PUMPKIN_STEM, TORCHFLOWER_CROP, PITCHER_CROP, COCOA, NETHER_WART, SWEET_BERRY_BUSH,
                     GRASS_BLOCK, MOSS_BLOCK, PALE_MOSS_BLOCK, SUGAR_CANE, CACTUS, BAMBOO, BAMBOO_SAPLING, SEAGRASS, KELP, KELP_PLANT, CAVE_VINES, CAVE_VINES_PLANT, TWISTING_VINES, WEEPING_VINES, PINK_PETALS, WILDFLOWERS, LEAF_LITTER, FIREFLY_BUSH, SHORT_DRY_GRASS, TALL_DRY_GRASS, SHORT_GRASS, FERN, CRIMSON_ROOTS, WARPED_ROOTS, CRIMSON_FUNGUS, WARPED_FUNGUS, CRIMSON_NYLIUM, WARPED_NYLIUM -> true;
                default -> false;
            };
            case HONEYCOMB -> switch (material) {
                case CHISELED_COPPER, COPPER_BARS, COPPER_BLOCK, COPPER_BULB, COPPER_CHAIN, COPPER_CHEST, COPPER_DOOR, COPPER_GOLEM_STATUE, COPPER_GRATE, COPPER_LANTERN, COPPER_TRAPDOOR, CUT_COPPER, CUT_COPPER_SLAB, CUT_COPPER_STAIRS, LIGHTNING_ROD,
                     EXPOSED_CHISELED_COPPER, EXPOSED_COPPER, EXPOSED_COPPER_BARS, EXPOSED_COPPER_BULB, EXPOSED_COPPER_CHAIN, EXPOSED_COPPER_CHEST, EXPOSED_COPPER_DOOR, EXPOSED_COPPER_GOLEM_STATUE, EXPOSED_COPPER_GRATE, EXPOSED_COPPER_LANTERN, EXPOSED_COPPER_TRAPDOOR, EXPOSED_CUT_COPPER, EXPOSED_CUT_COPPER_SLAB, EXPOSED_CUT_COPPER_STAIRS, EXPOSED_LIGHTNING_ROD,
                     WEATHERED_CHISELED_COPPER, WEATHERED_COPPER, WEATHERED_COPPER_BARS, WEATHERED_COPPER_BULB, WEATHERED_COPPER_CHAIN, WEATHERED_COPPER_CHEST, WEATHERED_COPPER_DOOR, WEATHERED_COPPER_GOLEM_STATUE, WEATHERED_COPPER_GRATE, WEATHERED_COPPER_LANTERN, WEATHERED_COPPER_TRAPDOOR, WEATHERED_CUT_COPPER, WEATHERED_CUT_COPPER_SLAB, WEATHERED_CUT_COPPER_STAIRS, WEATHERED_LIGHTNING_ROD,
                     OXIDIZED_CHISELED_COPPER, OXIDIZED_COPPER, OXIDIZED_COPPER_BARS, OXIDIZED_COPPER_BULB, OXIDIZED_COPPER_CHAIN, OXIDIZED_COPPER_CHEST, OXIDIZED_COPPER_DOOR, OXIDIZED_COPPER_GOLEM_STATUE, OXIDIZED_COPPER_GRATE, OXIDIZED_COPPER_LANTERN, OXIDIZED_COPPER_TRAPDOOR, OXIDIZED_CUT_COPPER, OXIDIZED_CUT_COPPER_SLAB, OXIDIZED_CUT_COPPER_STAIRS, OXIDIZED_LIGHTNING_ROD -> true;
                default -> false;
            };
            case FLINT_AND_STEEL, FIRE_CHARGE -> switch (material) {
                case TNT, CREEPER_HEAD, CAMPFIRE, SOUL_CAMPFIRE,
                     CANDLE, WHITE_CANDLE, ORANGE_CANDLE, MAGENTA_CANDLE, LIGHT_BLUE_CANDLE, YELLOW_CANDLE, LIME_CANDLE, PINK_CANDLE, GRAY_CANDLE, LIGHT_GRAY_CANDLE, CYAN_CANDLE, PURPLE_CANDLE, BLUE_CANDLE, BROWN_CANDLE, GREEN_CANDLE, RED_CANDLE, BLACK_CANDLE,
                     CANDLE_CAKE, WHITE_CANDLE_CAKE, ORANGE_CANDLE_CAKE, MAGENTA_CANDLE_CAKE, LIGHT_BLUE_CANDLE_CAKE, YELLOW_CANDLE_CAKE, LIME_CANDLE_CAKE, PINK_CANDLE_CAKE, GRAY_CANDLE_CAKE, LIGHT_GRAY_CANDLE_CAKE, CYAN_CANDLE_CAKE, PURPLE_CANDLE_CAKE, BLUE_CANDLE_CAKE, BROWN_CANDLE_CAKE, GREEN_CANDLE_CAKE, RED_CANDLE_CAKE, BLACK_CANDLE_CAKE -> true;
                default -> false;
            };
            case WHITE_DYE, ORANGE_DYE, MAGENTA_DYE, LIGHT_BLUE_DYE, YELLOW_DYE, LIME_DYE, PINK_DYE, GRAY_DYE, LIGHT_GRAY_DYE, CYAN_DYE, PURPLE_DYE, BLUE_DYE, BROWN_DYE, GREEN_DYE, RED_DYE, BLACK_DYE, GLOW_INK_SAC, INK_SAC -> switch (material) {
                case ACACIA_SIGN, ACACIA_WALL_SIGN, ACACIA_HANGING_SIGN, ACACIA_WALL_HANGING_SIGN, BAMBOO_SIGN, BAMBOO_WALL_SIGN, BAMBOO_HANGING_SIGN, BAMBOO_WALL_HANGING_SIGN, BIRCH_SIGN, BIRCH_WALL_SIGN, BIRCH_HANGING_SIGN, BIRCH_WALL_HANGING_SIGN, CHERRY_SIGN, CHERRY_WALL_SIGN, CHERRY_HANGING_SIGN, CHERRY_WALL_HANGING_SIGN, CRIMSON_SIGN, CRIMSON_WALL_SIGN, CRIMSON_HANGING_SIGN, CRIMSON_WALL_HANGING_SIGN, DARK_OAK_SIGN, DARK_OAK_WALL_SIGN, DARK_OAK_HANGING_SIGN, DARK_OAK_WALL_HANGING_SIGN, JUNGLE_SIGN, JUNGLE_WALL_SIGN, JUNGLE_HANGING_SIGN, JUNGLE_WALL_HANGING_SIGN, MANGROVE_SIGN, MANGROVE_WALL_SIGN, MANGROVE_HANGING_SIGN, MANGROVE_WALL_HANGING_SIGN, OAK_SIGN, OAK_WALL_SIGN, OAK_HANGING_SIGN, OAK_WALL_HANGING_SIGN, PALE_OAK_SIGN, PALE_OAK_WALL_SIGN, PALE_OAK_HANGING_SIGN, PALE_OAK_WALL_HANGING_SIGN, SPRUCE_SIGN, SPRUCE_WALL_SIGN, SPRUCE_HANGING_SIGN, SPRUCE_WALL_HANGING_SIGN, WARPED_SIGN, WARPED_WALL_SIGN, WARPED_HANGING_SIGN, WARPED_WALL_HANGING_SIGN -> true;
                default -> false;
            };
            case WATER_BUCKET, LAVA_BUCKET, POWDER_SNOW_BUCKET, POTION, SPLASH_POTION, LINGERING_POTION -> material == Material.CAULDRON;
            case BUCKET -> switch (material) {
                case WATER, LAVA, POWDER_SNOW, WATER_CAULDRON, LAVA_CAULDRON, POWDER_SNOW_CAULDRON -> true;
                default -> false;
            };
            case GLASS_BOTTLE -> material == Material.WATER || material == Material.WATER_CAULDRON;
            case SHEARS -> switch (material) {
                case PUMPKIN, BEEHIVE, BEE_NEST -> true;
                default -> false;
            };
            case BRUSH -> material == Material.SUSPICIOUS_SAND || material == Material.SUSPICIOUS_GRAVEL;
            case ENDER_EYE -> material == Material.END_PORTAL_FRAME;
            case LEAD -> switch (material) {
                case ACACIA_FENCE, BAMBOO_FENCE, BIRCH_FENCE, CHERRY_FENCE, CRIMSON_FENCE, DARK_OAK_FENCE, JUNGLE_FENCE, MANGROVE_FENCE, NETHER_BRICK_FENCE, OAK_FENCE, PALE_OAK_FENCE, SPRUCE_FENCE, WARPED_FENCE -> true;
                default -> false;
            };
            case GLOWSTONE_DUST -> material == Material.RESPAWN_ANCHOR;
            case WRITABLE_BOOK, WRITTEN_BOOK -> material == Material.LECTERN;
            default -> false;
        };
    }

    public static boolean isUsable(final Material material) {
        return switch (material) {
            case APPLE, BAKED_POTATO, BEEF, BEETROOT, BEETROOT_SOUP, BREAD, CARROT, CHICKEN, CHORUS_FRUIT, COD, COOKED_BEEF, COOKED_CHICKEN, COOKED_COD, COOKED_MUTTON, COOKED_PORKCHOP, COOKED_RABBIT, COOKED_SALMON, COOKIE, DRIED_KELP,
                 ENCHANTED_GOLDEN_APPLE, GLOW_BERRIES, GOLDEN_APPLE, GOLDEN_CARROT, HONEY_BOTTLE, MELON_SLICE, MILK_BUCKET, MUSHROOM_STEW, MUTTON, OMINOUS_BOTTLE, POISONOUS_POTATO, PORKCHOP, POTATO, POTION, PUFFERFISH, PUMPKIN_PIE,
                 RABBIT, RABBIT_STEW, ROTTEN_FLESH, SALMON, SPIDER_EYE, SUSPICIOUS_STEW, SWEET_BERRIES, TROPICAL_FISH,
                 EGG, ENDER_EYE, ENDER_PEARL, EXPERIENCE_BOTTLE, FIREWORK_ROCKET, LINGERING_POTION, SNOWBALL, SPLASH_POTION, WIND_CHARGE -> true;
            default -> false;
        };
    }
}